# Generated by Django 5.2.8 on 2025-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_timelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('work', 'Work Experience'), ('army', 'Call of Duty')], max_length=20),
        ),
    ]
