# Generated by Django 5.2.8 on 2025-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_timelineitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('linkedin_link', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
            ],
        ),
    ]
