# Generated by Django 5.2.8 on 2025-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personalinfo/'),
        ),
    ]
